services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - GRPC_PORT=:50051
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - "50051:50051"

  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
