services:
  app:
    build: .
    container_name: ir-app
    depends_on:
      - db
      - cache
    environment:
      - TEMPORAL_ADDR=temporal:7233
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CACHE_URL=redis://default:redispassword@cache:6379
      - TASK_QUEUE=items-repository
    networks:
      - ir-network
      - temporal-network

  db:
    image: postgres:17
    container_name: ir-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ir-network

  cache:
    image: redis:8-alpine
    container_name: ir-cache
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - cachedata:/data
    networks:
      - ir-network

volumes:
  pgdata:
  cachedata:

networks:
  ir-network:
    driver: bridge
  temporal-network:
    external: true
