// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/google/uuid"
	"time"
)

type Brand struct {
	Name string
}

type Category struct {
	Name  string
	Label *string
}

type Product struct {
	ProductID uuid.UUID
	Name      string
	Brand     *string
	Category  *string
	Price     int64
	Rating    *float32
}

type ProductCharacteristic struct {
	ProductID         uuid.UUID
	Description       *string
	Weight            *int32
	QuantityInPackage *int32
	ShelfLife         time.Duration
	StorageConditions *string
	Nutrition         *string
}
