// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/google/uuid"
)

type Item struct {
	ID            uuid.UUID
	Name          string
	Description   string
	Type          string
	WeightInGrams int32
	Amount        int32
}
